### ISSUE TITLE
Enable Trakt Progress

### ISSUE THREAD

**Issue by Sarafian** [Stremio/stremio-core#508] opened 2023-08-28 07:37 UTC
I've search for prior issues etc and I've not found this mentioned outside general older trakt issues.

Trakt integration is core to stremio since you configure this from the very beginning without an add-on etc. What I find strange and lacking is that you can't actually access the trakt progress section, to continue watching shows from where you left of. Now, stremio does have centralized status keeping, which does allow continueity between different players using the same account but any show that you had watched before moving to stremio will not show. 

For example, after I moved to stremio, I realized that I had no idea that some other shows had started season 2 until I browsed the trakt's progress website and I realized that I was only watching what was easy to access and continue from the default options.

At a minimum, I think there should be a list for progress like you have for the history and lists. Actually the history options have no value in my opinion.

**Comment by TRtomasz** [comment] 2023-08-28 08:39
closing as duplicate of https://github.com/Stremio/stremio-features/issues/344 
in the future please use stremio-feature for new features requests

**Closed as completed by TRtomasz** 2023-08-28 08:39 UTC

**Comment by Sarafian** [comment] 2023-08-28 09:02
This is not the same. I'll use the right repository. Didn't notice it. My apologies.

The link feature mentions library and watchlists. I'm suggesting that the progress is shown. Would you like me to create a dublicate in the stremio-features repo?

**Comment by TRtomasz** [comment] 2023-08-28 15:46
@Sarafian  it is basically the same and it is about 2way trakt integration, anway will not be implemented anytime soon.

**Comment by oathzed** [comment] 2024-01-01 01:27
> @Sarafian it is basically the same and it is about 2way trakt integration, anway will not be implemented anytime soon.

But it will be implemented? XD
