### ISSUE TITLE
Localsearch: Returns completely irrelevant results at the bottom of the list

### ISSUE THREAD

**Issue by jaruba** [Stremio/stremio-core#148] opened 2020-04-01 14:11 UTC
While testing the local search, I went across this interesting case.

To reproduce:
- search query: "a series of unfortunate events"
- dataset size: 10k
- maximum results: 15

Screenshot of results:
<img width="753" alt="Screen Shot 2020-04-01 at 17 07 45" src="https://user-images.githubusercontent.com/1777923/78146851-62efda00-743b-11ea-9050-a0273eafff84.png">

Screenshot of Stremio's current results: (which seem much more accurate)
<img width="564" alt="Screen Shot 2020-04-01 at 17 09 40" src="https://user-images.githubusercontent.com/1777923/78147036-a0546780-743b-11ea-900a-ee27dba56388.png">

**Comment by MartinKavik** [comment] 2020-04-01 14:56
> Returns completely irrelevant results at the bottom of the list

Which results do you mean?
For instance, the last one - "LEGO DC Comics Super Heroes: **A**quaman - Rage of **A**ntlantis" matches by prefix ("**a** series of unfortunate events").

Default tokenizer only split search query by whitespace so `a` is a valid token and I can't determine if it's a bug or a feature => what's the expected behavior / results?

**Comment by jaruba** [comment] 2020-04-01 15:22
Removed "a" and searched for "series of unfortunate events":
<img width="589" alt="Screen Shot 2020-04-01 at 18 13 23" src="https://user-images.githubusercontent.com/1777923/78154182-9f740380-7444-11ea-8a8b-de1877775622.png">

The expected behaviour is to get results that are relevant to the search query from a human perspective. Currently Stremio gives results that are relevant from a human perspective, while local search does not.

In both the screenshoted cases all the results after the first 2 seem meaningless. As we are working with many movie / series titles, it might indeed be a good idea to not match things based on `a`, `the`, and other very general words used in the majority of movie / series titles, as it will bring many false positives.

But even removing "a" still brings weird responses, and in both those cases i get sexual related content which means we simply can't make this search live until the results become less _fluid_.

Maybe a good idea would be to ignore search results with scores that stray away too much from the primary results?

**Comment by MartinKavik** [comment] 2020-06-25 17:24
> Maybe a good idea would be to ignore search results with scores that stray away too much from the primary results?

I've improved an algorithm a bit and search results with the score lower than the predefined threshold are ignored. The default threshold is now set to `first_result_score * 0.48`.

Updated version deployed to https://stremio-search.netlify.app/

**Comment by Ivshti** [comment] 2020-07-01 14:22
@jaruba can you please check?

**Comment by jaruba** [comment] 2020-07-01 15:04
this seems better for queries that are expected to have few results, like `a series of unfortunate events` and `seinfeld`

but i see some serious issues regarding ordering when used for queries that are expected to have many results:

- results for `avengers`:
<img width="620" alt="Screen Shot 2020-07-01 at 17 53 25" src="https://user-images.githubusercontent.com/1777923/86258717-cd8fed80-bbc3-11ea-895a-716eb3844dae.png">

^ in this case the first result is a series from 1961 (which definitely shouldn't be on top, the ratings are ok but it has very few votes on IMDB), the second and third results are cartoons, one has a rating of 2.7 and on the 4th place there's a 1998 movie that scores 3.8.. "Avengers Endgame" which is probably the most popular of the results is last on the 11th place, while "The Avengers" movie which should of been expected to be on top is on the 5th place

- results for `superman`:

<img width="558" alt="Screen Shot 2020-07-01 at 18 00 11" src="https://user-images.githubusercontent.com/1777923/86259536-d03f1280-bbc4-11ea-9e67-51777f74b8c7.png">

^ the results for "superman" are missing the latest movie releases: Batman v Superman: Dawn of Justice (2016), Man of Steel (2013), it's also missing the well known series: The New Adventures of Superman (1993), and the latest series based on the story: Smallville (2001) (aka "Young Superman")

**Comment by jaruba** [comment] 2020-07-01 15:12
are we checking the aka titles too when searching? as for the case of `superman`, the aka titles do include "superman" as a word, while not all the primary titles include it

**Comment by MartinKavik** [comment] 2020-07-01 15:23
Source dataset is https://stremio-search.netlify.app/data/cinemeta_20_000.json. The search uses only field `name`. If you want to integrate custom logic (e.g. boosting according to IMDB score or title aliases) I would need more detailed specifications and updated dataset because it won't be trivial to implement correctly.

**Comment by jaruba** [comment] 2020-07-01 15:40
Cinemeta has an internal popularity score, a simplistic solution to this would be to sort the items with the same score by their popularity. Notice that in the case of `avengers` the first 6 results have the same exact score (`31.557823863034535`).

This would still not fix the fact that "Avengers: Endgame", which should be much higher up in the results, would still be last on the 11th place.

Maybe a better solution would be to ignore the matching score after the results have been selected, and simply sort all the results by popularity at the end.

I'd say that at this point, the best results would be gotten by including the aka titles in the search too (i realise that this would decrease the speed of searching though) and sort all final results by their popularity.

**Comment by jaruba** [comment] 2020-07-01 15:43
What I'm not sure about is if we can get only the english aka titles, as the ones in other languages might create too many false positives in the results.

**Comment by jaruba** [comment] 2020-07-01 15:44
What I'm not sure about is if we can get only the english aka titles, as the ones in other languages would increase the dataset size and create too many false positives in the results, although it would result in better search results for users that will search in their native languages.

**Comment by jaruba** [comment] 2020-07-01 15:53
I'm also curious why a dataset of 20k items include items that have scores of 2.7 and 3.8 on IMDB.

@Ivshti how do we choose what is added to the dataset? should it not include only popular items?

**Comment by Ivshti** [comment] 2020-07-01 15:55
It should not include unpopular items and indeed it should include only popular ones

I didn’t have much time to tinker with it so I just exported the top N by Stremio popularity. @jaruba You should tweak the dataset so that it works better

**Comment by MartinKavik** [comment] 2020-07-08 14:36
>  @jaruba You should tweak the dataset so that it works better. It’s just a simple export of the top catalog of cinemeta, by joining the first N/100 pages.

@jaruba Did you have time to prepare ideal dataset from your point of view? If not, I'll try to do it according to the comments above. Thanks.

**Comment by jaruba** [comment] 2020-07-09 14:05
@MartinKavik I'll be able to do it at the start of next week.

**Comment by jaruba** [comment] 2020-07-14 11:33
Let's try with this export, I filtered by:
- `imdbRating` exists
- `imdbRating` is larger then `5`
- `popularity` exists

The export includes 10k movies and 10k series, for each movie and series it also includes `imdbRating` and `popularity`.

It does not include movie akas, as we don't seem to have those available in Cinemeta right now.

[export.zip](https://github.com/Stremio/stremio-core/files/4918515/export.zip)

**Comment by jaruba** [comment] 2020-07-14 11:55
We might also consider basing the export on other (more accurate) popularity lists from IMDB or similar qualified reviewer databases if required.

**Comment by MartinKavik** [comment] 2020-07-17 16:41
I've tried some algorithms for boosting/sorting according to IMDB Rating and Popularity. And the best one is probably
```rust
let imdb_rating_boost = (record.imdb_rating / max_imdb_rating * imdb_rating_weight).exp();  // `exp2()` should be also ok if it's faster
...
let score = original_score * imdb_rating_boost * ...
```
where you can set `imdb_rating_weight` through a variable `IMDB rating weight` - see the picture below:

![image](https://user-images.githubusercontent.com/18517402/87809165-32517600-c85b-11ea-9ea2-4062781f8b34.png)

I've also added field `Score threshold (%)` - `50` would filter out all results that have the score lower than 50% of the top result. `0` effectively disables filtering by score.

These boosts helps with the most cases (including the `Avengers: Endgame` problem your mentioned above). However it doesn't help with `superman` - aka titles would be necessary for more relevant results.

Deployed as usual on https://stremio-search.netlify.app/

Q: How is `popularity` computed? And does it have a maximum value? Thanks.

**Comment by jaruba** [comment] 2020-07-30 12:56
Sorry for the late reply, i was very busy in this time

The results seem much better now imo, aka titles would be a nice to have too, but we can't get them from Cinemeta right now.

There's one more interesting case I've found:
<img width="563" alt="Screen Shot 2020-07-30 at 15 52 54" src="https://user-images.githubusercontent.com/1777923/88925251-f1a32500-d27c-11ea-9625-26ad46c84bbd.png">

But when adding a `-` we get:
<img width="721" alt="Screen Shot 2020-07-30 at 15 54 48" src="https://user-images.githubusercontent.com/1777923/88925332-0da6c680-d27d-11ea-8892-199c82a300bd.png">

I'm wondering what the underlying issue is here, and why the results from `spider-` don't show for `spider` too.

**Comment by jaruba** [comment] 2020-07-30 12:56
Regarding:
> Q: How is popularity computed? And does it have a maximum value? Thanks.

Only @Ivshti could answer that.

**Comment by MartinKavik** [comment] 2020-09-16 10:46
- Ad `spider` - I've improved the tokenizer and it also takes into account dashes (`-`) now. So it should work as expected.
- Ad `popularity` - Ivo's answer on Slack - `it's moviedb_rating*A * how_many_times_In_stremio_Lib*B,
doesn't have a max value`. I've updated code to reflect that with some minor search algorithm improvements.

**Comment by jaruba** [comment] 2020-09-18 12:08
@MartinKavik I think this is good, or as close as we're going to get to it, I can't think of any further improvements right now.

**Comment by elpiel** [comment] 2023-03-23 14:26
Since we're already looking to integrate this crate in core and provide autocompletion with it, I'm closing this issue and will link it for reference.

**Closed by elpiel** 2023-03-23 14:26 UTC
