### ISSUE TITLE
Back button on navbar doesnt work

### ISSUE THREAD

**Issue by lemonking909** [Stremio/stremio-core#373] opened 2022-09-07 15:23 UTC
As per title, after watching 2 episodes of anything back to back, then trying to navigate thru the interface, back button on navbar doesnt work. Pressing it just made the navbar go away. Pressing home still works, just the back button having this issue. The one in the app, on top left also works.

ps
This is on android app. Phone is Galaxy S9. App version is 1.5.5

**Comment by TRtomasz** [comment] 2022-09-07 15:39
closing as duplicate of https://github.com/Stremio/stremio-bugs/issues/313 please use stremio-bugs in the future to report issues

**Closed by TRtomasz** 2022-09-07 15:39 UTC
