### ISSUE TITLE
Stremio doesn't have an 'Exit' menu option

### ISSUE THREAD

**Issue by Zeioth** [Stremio/stremio-core#179] opened 2020-08-16 22:11 UTC
**Expected behavior:**
Click menu > Exit

**Current behavior:**
There's no button to close the program. Manually sending the exit signal to the program, leaves it running in background.

System: I3 Manjaro, or any other system without system window buttons.

**Comment by TRtomasz** [comment] 2020-08-17 07:38
Duplicate of https://github.com/Stremio/stremio-bugs/issues/207

**Closed by TRtomasz** 2020-08-17 07:38 UTC
